"use client";

const statusToneMap: Record<string, string> = {
  online: "success",
  offline: "warning",
  busy: "warning",
  not_installed: "neutral",
  installing: "accent",
  collecting: "accent",
  unknown: "neutral",
  draft: "neutral",
  ready: "success",
  completed: "success",
  pending: "neutral",
  running: "accent",
  retry: "warning",
  success: "success",
  canceled: "neutral",
  partial: "warning",
  failure: "danger",
  failed: "danger",
  low: "accent",
  medium: "warning",
  high: "danger",
  critical: "danger",
  open: "accent",
  closed: "neutral",
  ignored: "neutral",
  fixed: "success",
  enabled: "success",
  disabled: "neutral",
  confirmed: "success",
  rejected: "neutral",
  inconclusive: "warning",
  error: "danger",
  skipped: "neutral",
  not_applicable: "neutral",
  passive: "accent",
  active: "success",
};

const statusLabelMap: Record<string, string> = {
  online: "在线",
  offline: "离线",
  busy: "忙碌",
  not_installed: "未安装",
  installing: "安装中",
  collecting: "正在采集",
  unknown: "未知",
  draft: "待准备",
  ready: "可执行",
  completed: "已完成",
  pending: "排队中",
  running: "运行中",
  retry: "重试中",
  success: "成功",
  canceled: "已中断",
  partial: "部分完成",
  failure: "失败",
  failed: "失败",
  low: "低危",
  medium: "中危",
  high: "高危",
  critical: "严重",
  open: "开放",
  closed: "关闭",
  ignored: "已忽略",
  fixed: "已修复",
  enabled: "启用",
  disabled: "停用",
  confirmed: "已确认",
  rejected: "已排除",
  inconclusive: "待确认",
  error: "探测异常",
  skipped: "已跳过",
  not_applicable: "不适用",
  passive: "被动匹配",
  active: "主动确认",
};

export default function StatusTag({ value }: { value: string | null | undefined }) {
  const normalized = String(value || "unknown").toLowerCase();
  const tone = statusToneMap[normalized] || "neutral";
  const label = statusLabelMap[normalized] || String(value || "未知");

  return <span className={`status-pill status-pill-${tone}`}>{label}</span>;
}
